### ISSUE TITLE
Linked products not appearing for custom videos on mobile

### ISSUE THREAD

**Issue by emailvenkatm** [bambuser/BambuserPlayerSDK-iOS#18] opened 2024-09-11 14:49 UTC
When using the Bambuser Player iOS SDK, related products show up correctly in the timeline for the sample video(vAtJH3xevpYTLnf1oHao) provided by Bambuser. However, when uploading and mapping our custom videos with related products via the Bambuser dashboard, the products do not appear in the timeline next to the player. But they are loading fine on
the web side. Wondering if we have to enable any settings for the video from the dashboard to make the products appear on the mobile device.

Steps to Reproduce:
Go to the Bambuser dashboard.
Upload a custom video.
Map products to the timeline for that video in the dashboard.
Load the video using the Bambuser Player in our app.
Related products are not appearing next to the player.

**Comment by saeidbasirnia** [comment] 2024-09-13 12:11
Hi!
Thanks for reporting this issue. I reported this and we'll investigate the issue and get back to you.

**Comment by saeidbasirnia** [comment] 2024-09-18 07:42
Hi @emailvenkatm, 
We were not able to reproduce this issue on our side and highlighted products are being shown as expected for pre-recorded videos as well as live videos.
Verified for both uploading "Live stream video" and "Publish video on-demand" when video source is `Pre Recorded`.

can you provide more information so we can look in more depth into your issue?
- What version of SDK you are using and if you're receiving any logs/events
- Which env you're using and showId

You can also try your show with one of demo projects. 
You can put your `showId` property in `DemoSettings.swift` and run the project.

Please let me know if this helps or we can look into your issue.

**Comment by saeidbasirnia** [comment] 2024-10-01 14:46
I'll close this issue but please feel free to re-open it if you're facing this issue.

**Closed by saeidbasirnia** 2024-10-01 14:46 UTC
Labels: help wanted
